import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from 'sonner';


import "./globals.css";
import ConvexClientProvider from "@/prividers/convex-client-provider";
import { ModalProvider } from "@/prividers/modal-privider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          {children}
          <Toaster />
          <ModalProvider />
        </ConvexClientProvider>
      </body>
    </html>
  );
}
